version: '3.8'

services:
  # Development container for MonlyAI (SQLite based)
  monlyai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monlyai-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=file:/app/database.sqlite
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./migrations:/app/migrations
      - whatsapp_sessions:/app/.wwebjs_auth
    networks:
      - monlyai-network

networks:
  monlyai-network:
    driver: bridge

volumes:
  whatsapp_sessions:
    driver: local
