version: '3.8'

services:
  # Development container for MonlyAI (SQLite based)
  monlyai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monlyai-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=file:/app/data/database.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./database.db:/app/data/database.db
      - ./migrations:/app/migrations
      - whatsapp_sessions:/app/.wwebjs_auth
      - ./client:/app/client  # For hot reload in development
      - ./server:/app/server  # For hot reload in development
    networks:
      - monlyai-network
    command: npm run dev

networks:
  monlyai-network:
    driver: bridge

volumes:
  whatsapp_sessions:
    driver: local
